# Generated by Django 2.1.4 on 2019-11-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=64, unique=True)),
                ('password', models.CharField(help_text='混合盐值的32位md5密码（md5(密码+盐值)）', max_length=32)),
                ('salt', models.CharField(help_text='盐值，6位随机字符串', max_length=6)),
                ('real_name', models.CharField(help_text='真实姓名', max_length=32)),
                ('mobile', models.CharField(help_text='手机号码', max_length=11)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='按钮名', max_length=32, unique=True)),
                ('event', models.CharField(help_text='按钮所对应的js方法名', max_length=32, unique=True)),
                ('type', models.CharField(help_text='按钮出发的操作类型', max_length=32)),
                ('sort', models.IntegerField(help_text='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='按钮名', max_length=32, unique=True)),
                ('pid', models.IntegerField(help_text='模块父级id')),
                ('sort', models.IntegerField(help_text='排序')),
                ('url', models.CharField(help_text='模块链接', max_length=128)),
                ('buttons', models.ManyToManyField(to='backend.Button')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名', max_length=32, unique=True)),
                ('desc', models.CharField(help_text='关于角色的描述', max_length=300)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('buttons', models.ManyToManyField(to='backend.Button')),
                ('modules', models.ManyToManyField(to='backend.Module')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Role'),
        ),
    ]
