# Generated by Django 2.1.4 on 2019-11-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.CharField(default='', help_text='手机号码', max_length=11),
        ),
        migrations.AlterField(
            model_name='admin',
            name='real_name',
            field=models.CharField(default='', help_text='真实姓名', max_length=32),
        ),
        migrations.AlterField(
            model_name='button',
            name='sort',
            field=models.IntegerField(default=0, help_text='排序'),
        ),
        migrations.AlterField(
            model_name='button',
            name='type',
            field=models.CharField(default='', help_text='按钮出发的操作类型', max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='pid',
            field=models.IntegerField(default=0, help_text='模块父级id'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sort',
            field=models.IntegerField(default=0, help_text='排序'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(default='', help_text='模块链接', max_length=128),
        ),
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.CharField(default='', help_text='关于角色的描述', max_length=300),
        ),
    ]
