# Generated by Django 2.1.4 on 2019-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191107_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='type',
            field=models.CharField(default='', help_text='按钮触发的操作类型', max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='模块名', max_length=32, unique=True),
        ),
    ]
