# Generated by Django 2.1.4 on 2019-11-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191121_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '顶级菜单'), (2, '中级菜单'), (3, '末级菜单')], default=0),
        ),
    ]
